project:
  type: website

website:
  title: "Mini project"
  navbar:
    left:
      - text: report
        href: report.ipynb
      - text: Q1:Max Dep Delay
        href: Q1.ipynb
      - text: Q2:Max Early Dep
        href: Q2.ipynb
      - text: Q3:Day Ranking
        href: Q3.ipynb
      - text: Q4:Avg Delay Airport
        href: Q4.ipynb
      - text: Q5:Airline Max Delay
        href: Q5.ipynb
      - text: Q6:Cancellations
        href: Q6.ipynb
      - text: Q7:Avg Flights 3 Days
        href: Q7.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

